project:
  type: website
  output-dir: docs

website:
  title: "Mauro Florez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - teaching.qmd
      - CV.qmd
      - gallery.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

