project:
  type: website
  output-dir: docs

website:
  title: "Mauro Florez"
  description: "Mauro Florez's Personal Website - Data Science, Statistics, and Photography"
  site-url: "https://mauroflorez.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - teaching.qmd
      - gallery.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

